### ISSUE TITLE
[Feature]: Add Mark as resolved functionality to report command 

### ISSUE THREAD

**Issue by sloth-ontabasco** [kurzgesagt-in-a-nutshell/birdbot#155]
- Add a button `Mark as Resolved
` to the embed generated by the report command that makes it inactive
- In active state the bot pings the mods with a link to the embed every 10 minutes

**Comment by arcinfini** [comment]
The content in the linked branch is out of date and has a lot of conflicts with master so I am tempted to restart on this if someone else does not get to it first or fix the conflicts. 

I do think the best choice is to restart and salvage what can be salvaged.

**Comment by arcinfini** [comment]
Closing this in favor of a ticketing feature instead
