### ISSUE TITLE
[Bug]: Moderation commands throw an error when trying to take action on user that has left server

### ISSUE THREAD

**Issue by sloth-ontabasco** [kurzgesagt-in-a-nutshell/birdbot#192]
### Discord Contact Details

183092910495891467

### Title

Mod commands fail when trying to take action on non existent server member 

### Reproduction Steps

- Run a moderation command that takes in a user ID as input
- Ensure the said user has left the server

### Expected Results

Command informs the user that member is not present in the server 

### Actual Results

An unhandled exception is thrown

### Relevant log output

```shell
https://discord.com/channels/414027124836532234/865321589919055882/1216113853918613607
```

**Comment by arcinfini** [comment]
This has now been implemented into master. Error handling will share if the member cannot be resolved in argument transformation.
