### ISSUE TITLE
[Bug]: `infractions` command shows old username.

### ISSUE THREAD

**Issue by s-mv** [kurzgesagt-in-a-nutshell/birdbot#205]
### Discord Contact Details

489437432484200480

### Title

`infractions` command shows old username instead of the current one.

### Reproduction Steps

Use `infractions` on a user whose username has changed since they joined the server (for instance user 971109558074343434, so `/infractions 971109558074343434`).

### Expected Results

The command should retrieve the member's current username (along with other information).

### Actual Results

The command retrieves the username stored in the database rather than the current one.
(This is most probably because the username's being retrieved from `user_name` instead of getting it using the member's ID.)

**Comment by arcinfini** [comment]
Resolved in #225
